//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cwrs.DataBase.VanHanhLienHo
{
    using System;
    using System.Collections.Generic;
    
    public partial class dien_bien_tb
    {
        public int dien_bien_code { get; set; }
        public int vi_tri_ref { get; set; }
        public int tu_van_ref { get; set; }
        public int loai_du_lieu_ref { get; set; }
        public double gia_tri { get; set; }
        public Nullable<System.DateTime> thoi_gian { get; set; }
        public int is_thuc_do { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public Nullable<int> deleted_status { get; set; }
        public string row_id { get; set; }
    }
}
