//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cwrs.DataBase.VanHanhLienHo
{
    using System;
    using System.Collections.Generic;
    
    public partial class don_vi_tb
    {
        public int don_vi_code { get; set; }
        public string ki_hieu { get; set; }
        public string mo_ta { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public Nullable<int> deleted_status { get; set; }
        public string row_id { get; set; }
        public string don_vi_name { get; set; }
    }
}
