//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cwrs.DataBase.VanHanhLienHo
{
    using System;
    using System.Collections.Generic;
    
    public partial class phuong_an_tb
    {
        public int phuong_an_code { get; set; }
        public int tu_van_ref { get; set; }
        public string phan_tich { get; set; }
        public string kien_nghi { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public Nullable<int> deleted_status { get; set; }
        public string row_id { get; set; }
    }
}
