//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cwrs.DataBase.VanHanhLienHo
{
    using System;
    using System.Collections.Generic;
    
    public partial class thiet_lap_kich_ban_detail_tb
    {
        public int thiet_lap_kich_ban_detail_code { get; set; }
        public Nullable<int> thiet_lap_kich_ban_ref { get; set; }
        public double muc_nuoc_ho { get; set; }
        public double dung_tich_ho { get; set; }
        public double luu_luong_du_bao { get; set; }
        public double luu_luong_phat_dien { get; set; }
        public double luu_luong_xa { get; set; }
        public double tong_tran { get; set; }
        public Nullable<System.DateTime> thoi_gian { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public Nullable<int> deleted_status { get; set; }
        public string row_id { get; set; }
    }
}
