//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cwrs.DataBase.VanHanhLienHo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tong_hop_tb
    {
        public int tong_hop_code { get; set; }
        public string phan_tich_nhan_xet { get; set; }
        public string tong_hop_tinh_toan { get; set; }
        public string kien_nghi_dieu_hanh { get; set; }
        public Nullable<System.DateTime> thoi_gian { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public Nullable<int> deleted_status { get; set; }
        public string row_id { get; set; }
    }
}
