//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cwrs.DataBase.VanHanhLienHo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tu_van_tb
    {
        public int tu_van_code { get; set; }
        public int don_vi_ref { get; set; }
        public int user_ref { get; set; }
        public Nullable<System.DateTime> thoi_gian { get; set; }
        public string nhan_xet_24h { get; set; }
        public string du_bao_24h { get; set; }
        public string phan_tich { get; set; }
        public string kien_nghi { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public Nullable<int> deleted_status { get; set; }
        public string row_id { get; set; }
        public string link { get; set; }
    }
}
