//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cwrs.DataBase.VanHanhLienHo
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tb
    {
        public int user_code { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string mo_ta { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public Nullable<int> deleted_status { get; set; }
        public string row_id { get; set; }
        public Nullable<int> account_status { get; set; }
        public string email { get; set; }
        public string dia_chi { get; set; }
        public string dien_thoai { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<int> don_vi_ref { get; set; }
        public string user_guid { get; set; }
    }
}
