//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cwrs.DataBase.VanHanhLienHo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_tri_tb
    {
        public int vi_tri_code { get; set; }
        public string mo_ta { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string last_modified_by { get; set; }
        public Nullable<System.DateTime> last_modified_at { get; set; }
        public Nullable<int> deleted_status { get; set; }
        public string row_id { get; set; }
        public string vi_tri_name { get; set; }
        public Nullable<int> vi_tri_type { get; set; }
    }
}
