//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cwrs.LogDB.LogDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_tb
    {
        public int id { get; set; }
        public string system { get; set; }
        public string file { get; set; }
        public string function { get; set; }
        public string messages { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<int> is_error { get; set; }
        public string type { get; set; }
    }
}
