//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cwrs.Lib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cwrs.Lib.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số liệu quan trắc tức thời.
        /// </summary>
        public static string _LakeGeneral_SoLieuQuanTracTucThoi {
            get {
                return ResourceManager.GetString("_LakeGeneral_SoLieuQuanTracTucThoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan trắc chất lượng nước.
        /// </summary>
        public static string BangThoiGianThuc_QuanTracChatLuongNuoc {
            get {
                return ResourceManager.GetString("BangThoiGianThuc_QuanTracChatLuongNuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan trắc hồ chứa.
        /// </summary>
        public static string BangThoiGianThuc_QuanTracHoChua {
            get {
                return ResourceManager.GetString("BangThoiGianThuc_QuanTracHoChua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan trắc lượng mưa.
        /// </summary>
        public static string BangThoiGianThuc_QuanTracLuongMua {
            get {
                return ResourceManager.GetString("BangThoiGianThuc_QuanTracLuongMua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan trắc mực nước sông.
        /// </summary>
        public static string BangThoiGianThuc_QuanTracMucNuoc {
            get {
                return ResourceManager.GetString("BangThoiGianThuc_QuanTracMucNuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin quan trắc tổng hợp dữ liệu thời gian thực.
        /// </summary>
        public static string BangThoiGianThuc_Title {
            get {
                return ResourceManager.GetString("BangThoiGianThuc_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BĐ.
        /// </summary>
        public static string Common_BaoDong {
            get {
                return ResourceManager.GetString("Common_BaoDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh&lt;/br&gt;báo.
        /// </summary>
        public static string Common_CanhBao {
            get {
                return ResourceManager.GetString("Common_CanhBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Common_ChiTiet {
            get {
                return ResourceManager.GetString("Common_ChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ mặn&lt;/br&gt;(‰).
        /// </summary>
        public static string Common_DoMan {
            get {
                return ResourceManager.GetString("Common_DoMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So với 0.8 ‰&lt;/br&gt;(Mức tới hạn cây lúa).
        /// </summary>
        public static string Common_DoManSoSanh {
            get {
                return ResourceManager.GetString("Common_DoManSoSanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In báo cáo.
        /// </summary>
        public static string Common_InBaoCao {
            get {
                return ResourceManager.GetString("Common_InBaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MN(m).
        /// </summary>
        public static string Common_MucNuoc {
            get {
                return ResourceManager.GetString("Common_MucNuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập từ khóa.
        /// </summary>
        public static string Common_NhapTuKhoa {
            get {
                return ResourceManager.GetString("Common_NhapTuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q đến&lt;/br&gt;(m&lt;sup&gt;3&lt;/sup&gt;/s).
        /// </summary>
        public static string Common_QDen {
            get {
                return ResourceManager.GetString("Common_QDen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q xả&lt;/br&gt;(m&lt;sup&gt;3&lt;/sup&gt;/s).
        /// </summary>
        public static string Common_QXa {
            get {
                return ResourceManager.GetString("Common_QXa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo.
        /// </summary>
        public static string Common_Report {
            get {
                return ResourceManager.GetString("Common_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So sánh.
        /// </summary>
        public static string Common_SoSanh {
            get {
                return ResourceManager.GetString("Common_SoSanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Common_STT {
            get {
                return ResourceManager.GetString("Common_STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string Common_TatCa {
            get {
                return ResourceManager.GetString("Common_TatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hồ.
        /// </summary>
        public static string Common_TenHo {
            get {
                return ResourceManager.GetString("Common_TenHo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên trạm.
        /// </summary>
        public static string Common_TenTram {
            get {
                return ResourceManager.GetString("Common_TenTram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string Common_ThoiGian {
            get {
                return ResourceManager.GetString("Common_ThoiGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Common_TimKiem {
            get {
                return ResourceManager.GetString("Common_TimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xu&lt;/br&gt;thế.
        /// </summary>
        public static string Common_XuThe {
            get {
                return ResourceManager.GetString("Common_XuThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ mở cống.
        /// </summary>
        public static string CustomAsmLake_Ho_DoMoCong {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_DoMoCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ mở cửa tràn số.
        /// </summary>
        public static string CustomAsmLake_Ho_DoMoCuaTranSo {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_DoMoCuaTranSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung tích hồ.
        /// </summary>
        public static string CustomAsmLake_Ho_DungTichHo {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_DungTichHo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú: Lượng mưa được tính từ 7h sáng đến thời điểm hiện tại.
        /// </summary>
        public static string CustomAsmLake_Ho_GhiChuMua7h {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_GhiChuMua7h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu lượng.
        /// </summary>
        public static string CustomAsmLake_Ho_LuuLuong {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_LuuLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu lượng đến hồ.
        /// </summary>
        public static string CustomAsmLake_Ho_LuuLuongDenHo {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_LuuLuongDenHo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu lượng xả số.
        /// </summary>
        public static string CustomAsmLake_Ho_LuuLuongXaSo {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_LuuLuongXaSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mực nước hồ.
        /// </summary>
        public static string CustomAsmLake_Ho_MucNuocHo {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_MucNuocHo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mực nước kênh.
        /// </summary>
        public static string CustomAsmLake_Ho_MucNuocKenh {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_MucNuocKenh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số liệu quan trắc cống lấy nước.
        /// </summary>
        public static string CustomAsmLake_Ho_SoLieuQuanTracCongLayNuoc {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_SoLieuQuanTracCongLayNuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số liệu quan trắc mưa.
        /// </summary>
        public static string CustomAsmLake_Ho_SoLieuQuanTracMua {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_SoLieuQuanTracMua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số liệu quan trắc Tràn.
        /// </summary>
        public static string CustomAsmLake_Ho_SoLieuQuanTracTran {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_SoLieuQuanTracTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng lưu lượng xả.
        /// </summary>
        public static string CustomAsmLake_Ho_TongLuuLuongXa {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_TongLuuLuongXa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm đầu mối.
        /// </summary>
        public static string CustomAsmLake_Ho_TramDauMoi {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_TramDauMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm đo mưa số.
        /// </summary>
        public static string CustomAsmLake_Ho_TramDoMuaSo {
            get {
                return ResourceManager.GetString("CustomAsmLake_Ho_TramDoMuaSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số liệu quan trắc hồ.
        /// </summary>
        public static string CustomAsmLake_SoLieuQuanTracHo {
            get {
                return ResourceManager.GetString("CustomAsmLake_SoLieuQuanTracHo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Home_DangKy {
            get {
                return ResourceManager.GetString("Home_DangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Home_DangNhap {
            get {
                return ResourceManager.GetString("Home_DangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HỆ THỐNG THÔNG TIN.
        /// </summary>
        public static string Home_HeThongThongTin {
            get {
                return ResourceManager.GetString("Home_HeThongThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HỆ THỐNG THÔNG TIN QUẢN LÝ CÔNG TRÌNH THỦY LỢI VIỆT NAM.
        /// </summary>
        public static string Home_HeThongThongTinQuanLyCongTrinhThuyLoiVietNam {
            get {
                return ResourceManager.GetString("Home_HeThongThongTinQuanLyCongTrinhThuyLoiVietNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên hồ cần tìm....
        /// </summary>
        public static string Home_NhapTenHoCanTim {
            get {
                return ResourceManager.GetString("Home_NhapTenHoCanTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUNG ƯƠNG VỀ PHÒNG, CHỐNG THIÊN TAI.
        /// </summary>
        public static string Home_PhongChongLutBaoTrungUong {
            get {
                return ResourceManager.GetString("Home_PhongChongLutBaoTrungUong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÝ CÔNG TRÌNH THỦY LỢI VIỆT NAM.
        /// </summary>
        public static string Home_QuanLyCongTrinhThuyLoiVietNam {
            get {
                return ResourceManager.GetString("Home_QuanLyCongTrinhThuyLoiVietNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Httn.
        /// </summary>
        public static string Home_TheoHeThongThuyNong {
            get {
                return ResourceManager.GetString("Home_TheoHeThongThuyNong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Lưu vực.
        /// </summary>
        public static string Home_TheoLuuVuc {
            get {
                return ResourceManager.GetString("Home_TheoLuuVuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo sông.
        /// </summary>
        public static string Home_TheoSong {
            get {
                return ResourceManager.GetString("Home_TheoSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo Tỉnh.
        /// </summary>
        public static string Home_TheoTinh {
            get {
                return ResourceManager.GetString("Home_TheoTinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VĂN PHÒNG THƯỜNG TRỰC BAN CHỈ ĐẠO.
        /// </summary>
        public static string Home_VanPhongThuongTrucBanChiHuy {
            get {
                return ResourceManager.GetString("Home_VanPhongThuongTrucBanChiHuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VĂN PHÒNG THƯỜNG TRỰC BAN CHỈ ĐẠO TRUNG ƯƠNG VỀ PHÒNG, CHỐNG THIÊN TAI.
        /// </summary>
        public static string Home_VanPhongThuongTrucBanChiHuyPhongChongLutBaoTrungUong {
            get {
                return ResourceManager.GetString("Home_VanPhongThuongTrucBanChiHuyPhongChongLutBaoTrungUong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối phó với Bão và nước dâng.
        /// </summary>
        public static string Menu_AnhHuongBoiNgapLut {
            get {
                return ResourceManager.GetString("Menu_AnhHuongBoiNgapLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo.
        /// </summary>
        public static string Menu_BaoCao {
            get {
                return ResourceManager.GetString("Menu_BaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo chung.
        /// </summary>
        public static string Menu_BaoCao_BaoCaoChung {
            get {
                return ResourceManager.GetString("Menu_BaoCao_BaoCaoChung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo mưa giờ.
        /// </summary>
        public static string Menu_BaoCao_BaoCaoMuaGio {
            get {
                return ResourceManager.GetString("Menu_BaoCao_BaoCaoMuaGio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo mưa ngày.
        /// </summary>
        public static string Menu_BaoCao_BaoCaoMuaNgay {
            get {
                return ResourceManager.GetString("Menu_BaoCao_BaoCaoMuaNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo mưa trận.
        /// </summary>
        public static string Menu_BaoCao_BaoCaoMuaTran {
            get {
                return ResourceManager.GetString("Menu_BaoCao_BaoCaoMuaTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo dữ liệu tổng hợp.
        /// </summary>
        public static string Menu_BaoCao_TongHopDuLieuCongTrinh {
            get {
                return ResourceManager.GetString("Menu_BaoCao_TongHopDuLieuCongTrinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string Menu_DanhMuc {
            get {
                return ResourceManager.GetString("Menu_DanhMuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ chứa.
        /// </summary>
        public static string Menu_HoChua {
            get {
                return ResourceManager.GetString("Menu_HoChua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công trình đập.
        /// </summary>
        public static string Menu_HoChua_CongTrinhDap {
            get {
                return ResourceManager.GetString("Menu_HoChua_CongTrinhDap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công trình xả lũ.
        /// </summary>
        public static string Menu_HoChua_CongTrinhLu {
            get {
                return ResourceManager.GetString("Menu_HoChua_CongTrinhLu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chung.
        /// </summary>
        public static string Menu_HoChua_ThongTinChung {
            get {
                return ResourceManager.GetString("Menu_HoChua_ThongTinChung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ công trình.
        /// </summary>
        public static string Menu_HoSoCongTrinh {
            get {
                return ResourceManager.GetString("Menu_HoSoCongTrinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập liệu.
        /// </summary>
        public static string Menu_NhapLieu {
            get {
                return ResourceManager.GetString("Menu_NhapLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đo thủ công.
        /// </summary>
        public static string Menu_NhapLieu_DuLieuDoThuCong {
            get {
                return ResourceManager.GetString("Menu_NhapLieu_DuLieuDoThuCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý tin nhắn SMS.
        /// </summary>
        public static string Menu_NhapLieu_QuanLyTinNhanSMS {
            get {
                return ResourceManager.GetString("Menu_NhapLieu_QuanLyTinNhanSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tình hình sản xuất.
        /// </summary>
        public static string Menu_NhapLieu_ThongTinTinhHinhSanXuat {
            get {
                return ResourceManager.GetString("Menu_NhapLieu_ThongTinTinhHinhSanXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị.
        /// </summary>
        public static string Menu_QuanTri {
            get {
                return ResourceManager.GetString("Menu_QuanTri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string Menu_QuanTri_NguoiDung {
            get {
                return ResourceManager.GetString("Menu_QuanTri_NguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng.
        /// </summary>
        public static string Menu_QuanTri_NhomNguoiDung {
            get {
                return ResourceManager.GetString("Menu_QuanTri_NhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin dự báo.
        /// </summary>
        public static string Menu_ThongTinDuBao {
            get {
                return ResourceManager.GetString("Menu_ThongTinDuBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin quan trắc tổng hợp.
        /// </summary>
        public static string Menu_ThongTinQuanTracTongHop {
            get {
                return ResourceManager.GetString("Menu_ThongTinQuanTracTongHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình hình tiêu.
        /// </summary>
        public static string Menu_TinhHinhTieu {
            get {
                return ResourceManager.GetString("Menu_TinhHinhTieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình hình tưới.
        /// </summary>
        public static string Menu_TinhHinhTuoi {
            get {
                return ResourceManager.GetString("Menu_TinhHinhTuoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp sử dụng.
        /// </summary>
        public static string Menu_TroGiupSuDung {
            get {
                return ResourceManager.GetString("Menu_TroGiupSuDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chú giải bản đồ.
        /// </summary>
        public static string Menu_TroGiupSuDung_ChuGiaiBanDo {
            get {
                return ResourceManager.GetString("Menu_TroGiupSuDung_ChuGiaiBanDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Camera.
        /// </summary>
        public static string Menu_TroGiupSuDung_XemCamera {
            get {
                return ResourceManager.GetString("Menu_TroGiupSuDung_XemCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm mưa Vực Mấu.
        /// </summary>
        public static string VucMau_TramDoMuaDauMoi {
            get {
                return ResourceManager.GetString("VucMau_TramDoMuaDauMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm mưa Quỳnh Châu.
        /// </summary>
        public static string VucMau_TramDoMuaSo1 {
            get {
                return ResourceManager.GetString("VucMau_TramDoMuaSo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm mưa Nghĩa Hội.
        /// </summary>
        public static string VucMau_TramDoMuaSo2 {
            get {
                return ResourceManager.GetString("VucMau_TramDoMuaSo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm mưa Tân Thắng.
        /// </summary>
        public static string VucMau_TramDoMuaSo3 {
            get {
                return ResourceManager.GetString("VucMau_TramDoMuaSo3", resourceCulture);
            }
        }
    }
}
